language: node_js
node_js:
  - "4.1"
before_script:
  - npm install -g gulp bower
  - npm install
  - bower install
env:
  - NO_NYAN=true
script: gulp
notifications:
  slack: ece493capstone:hkULBLq0cnAz0XmKiROm06r7
before_deploy:
  - rm public/bin/.gitignore
deploy:
  provider: azure_web_apps
  verbose: true