language: node_js
node_js:
  - "4.1"
before_script:
  - npm install -g gulp bower
  - npm install
  - bower install
env:
  - NO_NYAN=true
script: gulp
notifications:
  slack: ece493capstone:hkULBLq0cnAz0XmKiROm06r7
deploy:
  provider: azure_web_apps
after_deploy:
  - gulp build-js
  - npm install -g forever
  - forever stopall
  - forever start polyball/Server.js